### ISSUE TITLE
Example for Resource Operation delegate

### ISSUE THREAD

**Issue by sunilk-m** [ContextMapper/context-mapper-examples#21]
It would be good to have an example of resource operation delegate to the service operation. I have defined a service and a resource and I am able to inject the service into the resource. I am not able to provide a delegation to the service operation from resource operation. My understanding is following should work but I am getting syntax error.
String createEmployee(@EmployeeDto emp) POST  path="/employee" DELEGATE @EmployeeService.addEmployee;
When I use ctrl spacebar I don't get Delegate in the proposal.

**Comment by stefan-ka** [comment]
Hi @sunilk-m 

Sorry for the late response! (I'm quite busy right now)

Actually `DELEGATE` is not a keyword, but the following terminal rule:

```
terminal DELEGATE :
  ('=>'|('delegates to'));
```

For some reason `delegates to` does not work (don't understand why right now), but you can use the following syntax:

```
String createEmployee(@EmployeeDto emp) POST path="/employee" => @EmployeeService.addEmployee ;
```

Let me know if this solves your issue and whether we can close this one.

Best regards,
Stefan

**Comment by sunilk-m** [comment]
Hi Stefan
=> worked. You can close the issue.

Regards
Sunil
