### ISSUE TITLE
DDD-sample UML BC diagrams contain only (first?) CargoBookingContext modules?

### ISSUE THREAD

**Issue by ejuntu** [ContextMapper/context-mapper-examples#23]
Hi! I've been diving into ContextMapper with great interest and enthusiasm, looks like a valuable tool for a system design at hand. However, when playing around with VS Code extension and DDD-Sample, I found out that if I generate PlantUML diagrams, the bounded context diagram is generated only for the first context (in this case Cargo Booking context). How can the UML diagrams be generated for other contexts in the cml file? I did not find documentation about this. I guess I could copy the parts to separate files, but that's not really in the spirit of automatic generation...

**Comment by stefan-ka** [comment]
Hi @ejuntu 

Thanks for getting in touch with us! Always nice to hear that @ContextMapper is used out there... :)

This should actually work; are you sure that you don't have any compilation problems in your `*.cml` file? An error in the file could maybe cause that our compiler can only read parts of the model.
Can you provide a minimal example to reproduce this issue?

Thanks and best regards,
Stefan

**Comment by stefan-ka** [comment]
@ejuntu

PS: I tested it with our DDD-sample and @ContextMapper v6.4.0 in VS Code; and I cannot reproduce the issue with that model.

**Comment by ejuntu** [comment]
Hi, now I can get correct output. There were Java error messages during generation, and I solved the problem by installing Java JDK. I thought I had installed it earlier, but anyway ContextMapper works OK now!
